services:
  russian-cup-backend:
    container_name: "russian-cup-backend-django"
    build:
      dockerfile: Dockerfile
      context: ..

    env_file:
        - .env
    ports:
        - "9090:9090"

  nginx-russian-cup:
    image: nginx:latest
    container_name: nginx-russian-cup
    ports:
      - "4443:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  russian-cup-pg:
    container_name: "russian-cup-pg"
    ports:
      - "5433:5432"
    image: postgres:15.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b1fddce8ae427c0d
    volumes:
      - "../pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -d postgres -U postgres
      retries: 5
      interval: 5s
      timeout: 7s

  rabbitmq-service:
      image: 'rabbitmq:3.6-management-alpine'
      ports:
        # The standard AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
      networks:
        - network
