# Generated by Django 5.2 on 2025-04-22 19:13

import django.db.models.deletion
import rc_backend.rc_app.models.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('title', models.TextField()),
                ('online', models.BooleanField()),
                ('place', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('registration_until', models.DateTimeField()),
                ('registration_start', models.DateTimeField()),
                ('max_participants', models.IntegerField()),
                ('min_participants', models.IntegerField()),
                ('competition_type', models.CharField(default=rc_backend.rc_app.models.enums.CompetitionEnum['NEW'], max_length=50)),
                ('on_moderation', models.CharField(default='PENDING', max_length=50)),
                ('is_shown', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FSP',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('head_email', models.EmailField(max_length=254)),
                ('is_federal', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCompetition',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('creation_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.competition')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to='rc_app.fsp')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to='rc_app.fsp')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('moderation_status', models.CharField(default='PENDING', max_length=20)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.competition')),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('place', models.IntegerField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_status', models.CharField(default=rc_backend.rc_app.models.enums.TeamInvitationEnum['PENDING'], max_length=20)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.profile')),
                ('inviter_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='FSPCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.competition')),
                ('fsp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsp_competitions', to='rc_app.fsp')),
            ],
            options={
                'unique_together': {('fsp_id', 'competition_id')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.profile')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team')),
            ],
            options={
                'unique_together': {('team_id', 'profile_id')},
            },
        ),
    ]
