# Generated by Django 5.2 on 2025-04-22 22:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='fsp',
            options={'verbose_name': 'Региональная ФСП', 'verbose_name_plural': 'Региональные ФСП'},
        ),
        migrations.AlterModelOptions(
            name='invitecompetition',
            options={'verbose_name': 'Приглашение соревнование', 'verbose_name_plural': 'Приглашения на соревнования'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='fsp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='moderation_status',
            field=models.CharField(
                choices=[('PENDING', 'На модерации'), ('APPROVED', 'Принято'), ('REJECTED', 'Отказать')],
                default='PENDING', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.CreateModel(
            name='MemberSearch',
            fields=[
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team')),
            ],
        ),
    ]
