# Generated by Django 5.2 on 2025-04-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rc_app', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(related_name='member_teams', to='rc_app.profile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_teams',
                                    to='rc_app.profile'),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
