# Generated by Django 5.2 on 2025-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rc_app', '0004_team_team_members_alter_team_leader_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='fsps',
            field=models.ManyToManyField(to='rc_app.fsp'),
        ),
        migrations.DeleteModel(
            name='FSPCompetition',
        ),
    ]
