# Generated by Django 5.2 on 2025-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rc_app', '0005_competition_fsps_delete_fspcompetition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionresult',
            name='competition_id',
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team'),
        ),
    ]
