# Generated by Django 5.2 on 2025-04-23 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0006_remove_competitionresult_competition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fsp',
            field=models.ForeignKey(default='65af6309-07f8-425b-8217-289173c430de', on_delete=django.db.models.deletion.CASCADE, to='rc_app.fsp'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('join_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('join_status', models.CharField(default='PENDING', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.profile')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rc_app.team')),
            ],
        ),
    ]
