# Generated by Django 5.2 on 2025-04-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0007_profile_fsp_joinrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='competition_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='competitionresult',
            old_name='result_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invitecompetition',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='joinrequest',
            old_name='join_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='joinrequest',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='membersearch',
            old_name='search_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='membersearch',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='leader_id',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='teaminvitation',
            old_name='invitation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='teaminvitation',
            old_name='inviter_team_id',
            new_name='inviter_team',
        ),
    ]
