# Generated by Django 5.2 on 2025-04-23 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_app', '0008_rename_competition_id_competition_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(choices=[('PRODUCT_PROGRAMMING', 'Продуктовое программирование'), ('ALGORITHMIC_PROGRAMMING', 'Программирование алгоритмическое'), ('IS_PROGRAMMING', 'Программирование систем информационной безопасности'), ('DRONE_PROGRAMMING', 'Программирование БАС'), ('ROBOTS_PROGRAMMING', 'Программирование робототехники')], max_length=100, verbose_name='Тип дисциплины')),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('OPEN', 'Открытые'), ('REGIONAL', 'Региональные'), ('FEDERAL', 'Всероссийские')], default='OPEN', max_length=50, verbose_name='Тип соревнования'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='on_moderation',
            field=models.CharField(choices=[('NEW', 'Новое'), ('PENDING', 'На модерации'), ('APPROVED', 'Принято'), ('REJECTED', 'Отказать')], default='NEW', max_length=50, verbose_name='На модерации'),
        ),
        migrations.AlterField(
            model_name='fsp',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='discipline',
            field=models.ForeignKey(default='2a483a89-5f60-49fe-b197-ddd45ec31e68', on_delete=django.db.models.deletion.CASCADE, to='rc_app.discipline'),
            preserve_default=False,
        ),
    ]
